//src\modules\common\components\base\generate\equipmentUniqueAbility-definitions.ts
import { Ability } from "../../../Ability";

export const fireAbilities: Ability[] = [
  {
    id: "fire-ability-1",
    name: "Fireball",
    abilityIs: "active",
    description: "Deals fire damage to enemies",
    icon: "fire",
  },
  {
    id: "fire-ability-2",
    name: "Inferno",
    abilityIs: "active",
    description: "Increases fire damage dealt to enemies",
    icon: "fire",
  },
  {
    id: "fire-ability-3",
    name: "Flame Shield",
    abilityIs: "active",
    description: "Absorbs damage and deals fire damage to attackers",
    icon: "fire",
  },
  {
    id: "fire-ability-4",
    name: "Blazing Speed",
    abilityIs: "active",
    description: "Increases movement speed and attack speed",
    icon: "fire",
  },
  {
    id: "fire-ability-5",
    name: "Pyroblast",
    abilityIs: "active",
    description: "Deals massive fire damage to enemies in a large area",
    icon: "fire",
  },
  {
    id: "fire-ability-6",
    name: "Fiery Aura",
    abilityIs: "active",
    description: "Deals fire damage to enemies within a small radius",
    icon: "fire",
  },
  {
    id: "fire-ability-7",
    name: "Scorching Ray",
    abilityIs: "active",
    description: "Deals fire damage to enemies in a straight line",
    icon: "fire",
  },
  {
    id: "fire-ability-8",
    name: "Incendiary Trap",
    abilityIs: "active",
    description: "Deals fire damage to enemies who trigger the trap",
    icon: "fire",
  },
  {
    id: "fire-ability-9",
    name: "Burning Fury",
    abilityIs: "active",
    description:
      "Increases damage dealt to enemies while reducing damage taken",
    icon: "fire",
  },
  {
    id: "fire-ability-10",
    name: "Volcanic Eruption",
    abilityIs: "active",
    description: "Deals massive fire damage to enemies in a large area",
    icon: "fire",
  },
];

export const waterAbilities: Ability[] = [
  {
    id: "water-ability-1",
    name: "Healing Wave",
    abilityIs: "active",
    description: "Restores health to allies",
    icon: "water",
  },
  {
    id: "water-ability-2",
    name: "Tidal Surge",
    abilityIs: "active",
    description: "Deals water damage to enemies",
    icon: "water",
  },
  {
    id: "water-ability-3",
    name: "Aquatic Shield",
    abilityIs: "active",
    description: "Absorbs damage and increases resistance to water damage",
    icon: "water",
  },
  {
    id: "water-ability-4",
    name: "Ocean's Blessing",
    abilityIs: "active",
    description: "Increases healing received and reduces damage taken",
    icon: "water",
  },
  {
    id: "water-ability-5",
    name: "Maelstrom",
    abilityIs: "active",
    description: "Deals massive water damage to enemies in a large area",
    icon: "water",
  },
  {
    id: "water-ability-6",
    name: "Water Walk",
    abilityIs: "active",
    description: "Allows the user to walk on water",
    icon: "water",
  },
  {
    id: "water-ability-7",
    name: "Ice Shard",
    abilityIs: "active",
    description: "Deals water damage to enemies and slows them down",
    icon: "water",
  },
  {
    id: "water-ability-8",
    name: "Floodgate",
    abilityIs: "active",
    description: "Deals water damage to enemies and knocks them back",
    icon: "water",
  },
  {
    id: "water-ability-9",
    name: "Tsunami",
    abilityIs: "active",
    description: "Deals massive water damage to enemies in a large area",
    icon: "water",
  },
  {
    id: "water-ability-10",
    name: "Hydrokinesis",
    abilityIs: "active",
    description:
      "Allows the user to manipulate water to deal damage to enemies",
    icon: "water",
  },
];

export const windAbilities: Ability[] = [
  {
    id: "wind-ability-1",
    name: "Gust",
    abilityIs: "active",
    description: "Deals wind damage to enemies",
    icon: "wind",
  },
  {
    id: "wind-ability-2",
    name: "Whirlwind",
    abilityIs: "active",
    description: "Deals wind damage to enemies and knocks them back",
    icon: "wind",
  },
  {
    id: "wind-ability-3",
    name: "Aerodynamic",
    abilityIs: "active",
    description: "Increases movement speed and reduces damage taken",
    icon: "wind",
  },
  {
    id: "wind-ability-4",
    name: "Storm Surge",
    abilityIs: "active",
    description: "Deals wind damage to enemies and increases damage dealt",
    icon: "wind",
  },
  {
    id: "wind-ability-5",
    name: "Cyclone",
    abilityIs: "active",
    description: "Deals massive wind damage to enemies in a large area",
    icon: "wind",
  },
  {
    id: "wind-ability-6",
    name: "Wind Shield",
    abilityIs: "active",
    description: "Absorbs damage and increases resistance to wind damage",
    icon: "wind",
  },
  {
    id: "wind-ability-7",
    name: "Air Blast",
    abilityIs: "active",
    description: "Deals wind damage to enemies and knocks them back",
    icon: "wind",
  },
  {
    id: "wind-ability-8",
    name: "Tornado",
    abilityIs: "active",
    description: "Deals massive wind damage to enemies in a large area",
    icon: "wind",
  },
  {
    id: "wind-ability-9",
    name: "Zephyr",
    abilityIs: "active",
    description: "Increases movement speed and reduces damage taken",
    icon: "wind",
  },
  {
    id: "wind-ability-10",
    name: "Aerial Mastery",
    abilityIs: "active",
    description: "Allows the user to manipulate wind to deal damage to enemies",
    icon: "wind",
  },
];

export const earthAbilities: Ability[] = [
  {
    id: "earth-ability-1",
    name: "Stone Fist",
    abilityIs: "active",
    description: "Deals earth damage to enemies",
    icon: "earth",
  },
  {
    id: "earth-ability-2",
    name: "Seismic Slam",
    abilityIs: "active",
    description: "Deals earth damage to enemies and stuns them",
    icon: "earth",
  },
  {
    id: "earth-ability-3",
    name: "Geological Shield",
    abilityIs: "active",
    description: "Absorbs damage and increases resistance to earth damage",
    icon: "earth",
  },
  {
    id: "earth-ability-4",
    name: "Mountain's Fury",
    abilityIs: "active",
    description: "Deals earth damage to enemies and increases damage dealt",
    icon: "earth",
  },
  {
    id: "earth-ability-5",
    name: "Earthquake",
    abilityIs: "active",
    description: "Deals massive earth damage to enemies in a large area",
    icon: "earth",
  },
  {
    id: "earth-ability-6",
    name: "Rock Armor",
    abilityIs: "active",
    description: "Increases damage reduction and absorbs damage",
    icon: "earth",
  },
  {
    id: "earth-ability-7",
    name: "Landslide",
    abilityIs: "active",
    description: "Deals earth damage to enemies and knocks them back",
    icon: "earth",
  },
  {
    id: "earth-ability-8",
    name: "Petrify",
    abilityIs: "active",
    description: "Turns enemies to stone, making them unable to move or attack",
    icon: "earth",
  },
  {
    id: "earth-ability-9",
    name: "Terraform",
    abilityIs: "active",
    description:
      "Allows the user to manipulate the earth to deal damage to enemies",
    icon: "earth",
  },
  {
    id: "earth-ability-10",
    name: "Gemstone Aura",
    abilityIs: "active",
    description: "Increases damage dealt and reduces damage taken",
    icon: "earth",
  },
];
